version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-#0e##29+62rgl_*la2+vp&w*x%h+3=bx#u8_r19$$%vxo3wz2pu"
      - "DJANGO_DEBUG=True"
  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      - "MYSQL_USER=user"
      - "MYSQL_DATABASE=mysql"
      - "MYSQL_PASSWORD=123321"
      - "MYSQL_ROOT_PASSWORD=123321"

volumes:
  mysql_data:

