# Generated by Django 4.1.5 on 2023-02-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('special_status', 'Can read all books'),)},
        ),
    ]
